DROP TABLE IF EXISTS thing;

CREATE TABLE thing
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  num INTEGER NOT NULL,
  stuff TEXT NOT NULL
);
